# Generated by Django 5.2.1 on 2025-06-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_payment_stripe_payment_url_payment_stripe_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="stripe_session_id",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
