# Generated by Django 5.2.1 on 2025-06-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_payment_stripe_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="stripe_payment_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
