# Generated by Django 5.2.1 on 2025-06-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
