# Generated by Django 5.2.1 on 2025-06-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_course_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price_id",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
